### ISSUE TITLE
Add Go to Home on Tic-Tac-Toe Game

### ISSUE THREAD

**Issue by krazykaushal** [MSTC-DA-IICT/Hacktoberfest22-Fun-with-JS#16]
Right now, On opening the Tic-tac-toe game, There is no go to Home page, and links to other games, Add such links there.

**Comment by pikameow420** [comment]
Hello, I'd like to work on this issue.

**Comment by krazykaushal** [comment]
Assigned to you @pikameow420  Good Luck

**Comment by pikameow420** [comment]
Links to all the games seem to be present in the navbar, on all pages, including the tic-tac-toe game.  @krazykaushal Could you please elaborate the bug? A visual representation of the bug shall be hugely beneficial.

**Comment by krazykaushal** [comment]
Sorry, my bad. I forgot to pull the latest commits.

**Comment by pikameow420** [comment]
@krazykaushal Alright no problem. Is it cool if I add a new issue and improve the home page?
