### ISSUE TITLE
Making the snake game

### ISSUE THREAD

**Issue by Jam-Burger** [MSTC-DA-IICT/Hacktoberfest22-Fun-with-JS#6]
We can add the basic snake game. The game should contain these functions:
- snake and controls
- food with random spawning
- snake becoming longer after eating the food
- walls and boundaries
-  game loses if hit by the wall or itself

Advanced functions:
- adding levels
- adding special food which increases more length

**Comment by krazykaushal** [comment]
Please make sure to add the game in a different folder. @Jam-Burger

**Comment by Jam-Burger** [comment]
okay! @krazykaushal
